name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
      
    - name: Directory Listing
      run: ls -l
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

      
    - name: Docker Build
      run: docker build -t hdev1004/ibo-bo .

    # DockerHub Login (push 하기 위해)
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    # Docker hub 로 push
    - name: Docker Hub push
      run: docker push hdev1004/ibo-bo


  # cafe24 실행
  run-docker-image-on-cafe24:
    needs: build-docker-image 
    runs-on: self-hosted

    steps:
    - name: docker pull
      run : docker pull hdev1004/ibo-bo

    - name: docker run new container
      run: docker run -d -p 7070:8080 --name ibo-bo hdev1004/ibo-bo

    - name: delete old docker image
      run: docker system prune -f
